### ISSUE TITLE
QSFP DDM

### ISSUE THREAD

**Issue by FLEngineer** [sfptotal/SFPTotal-Wizard#2]
Part Number: FTLC9551REPM-A6 

DDM doesn't appear to work on this QSFP although the mfg says it is supported.

09:37:48 > Read Table A0 add. 00,  128 byte(s) from 80
09:37:48 > R4A000807F
09:37:49 > 11CC0C800000000000000007FF0000230000320046494E4953415220434F5250202020200000906546544C43393535315245504D2D4136204130426807D000800207FFDE5858503043393120202020202020202031383033323120200C1067D5334845313231393541414141303120204E4F4B2020494E554941435042414160
09:37:49 > READ OK
09:39:02 > DDM reading has been started...
09:39:02 > Read Table A2 add. 00,  128 byte(s) from 80
09:39:02 > R1A200007F
09:39:02 > QERR:SFP_EMPTY
09:39:02 > DDM reading has been stopped.

**Comment by sfptotal** [comment]
Hi,

DDM reading functions supports since version 1051. Please, update the software to get access to new feature.
